myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import  home_view, login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tour.urls')),
    path('index/', home_view, name='index'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject/tour/urls.py
# import pandas as pd
from django.urls import path
from . import views

app_name = 'tour'
urlpatterns = [
    path('', views.index, name='index'),
    path('new_tour', views.NewTour.as_view(), name='new-tour'),
    path('charts/<str:type_chart>', views.Charts.as_view(), name='charts'),
    path('history', views.History.as_view(), name="history"),
    path('edit_tour/<int:id>', views.edit_tour, name='edit-tour'),
    path('delete/<int:id>', views.delete_tour, name='delete-tour')
]

myproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <title>NCPS Solaris - {% block title %}{% endblock title %}</title>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'base.css' %}">
        <link rel="stylesheet" href="{% static 'nav.css' %}">
        <link rel="stylesheet" href="{% static 'section.css' %}">
        <link rel="stylesheet" href="{% block css_file %}{% endblock css_file %}">        
    </head>

    <body>
        <div class="container-xxl container-fluid main">
            <nav class="navbar sticky-top">
                    {% include 'nav.html' %}
            </nav>
            <div class="section">
                {% block content %}
                {% endblock content %}
            </div>            
        </div>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    </body>

</html>

myproject/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
    <h5 class="text-center">Obchody infrastruktury elektroenergetycznej SN i nN w Narodowym Centrum Promieniowania Synchrotronowego w Krakowie.</h5>
    <img src={% static 'solaris.png' %} class="rounded mx-auto d-block" alt="solaris_picture">
{% endblock content %}

myproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}

{% block content %}
    {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message }}
        </div>
    {% endif %}


    <p>u: admin, h:admin</p>
    <form action="" method="POST" autocomplete="off">
        {% csrf_token %}
        <div class="container">
            <div class="row mb-3">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Użytkownik</label>
                <div class="col-sm-2">
                    {{ form.username }}
                </div>
            </div>
            <div class="row mb-3">
                <label for="inputPassword3" class="col-sm-2 col-form-label">Hasło</label>
                <div class="col-sm-2">
                    {{ form.password }}
                </div>
            </div>
            <button type='submit' class="btn btn-outline-success btn-sm">Zaloguj się</button>
        </div>
    </form>
{% endblock content %}

myproject/templates/nav.html
{% url 'login' as path_to_login %}
{% url 'logout' as path_to_logout %}
{% url 'tour:index' as path_to_index %}
{% url 'tour:new-tour' as path_to_new_tour %}
{% url 'tour:charts' as path_to_charts %}
{% url 'tour:history' as path_to_history %}


<ul class="nav nav-tabs bg-light">
    
    <li class="nav-item">
        <a class="nav-link {% if request.path == path_to_index %}active{% endif %}" aria-current="page" href="{{ path_to_index }}">Start</a>
    </li>

    <li class="nav-item">
        <a class="nav-link {% if request.path == path_to_new_tour %}active{% endif %}" href="{{ path_to_new_tour }}">Nowy Obchód</a>
    </li>

    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle {% if request.path == path_to_charts %}active{% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Wykresy
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" name="traf_temp" href="{% url 'tour:charts' 'trafo_temp' %}">Transformatory</a></li>
                    <li><a class="dropdown-item" name="ups_temp" href="{% url 'tour:charts' 'ups_temp' %}">UPSy</a></li>
                    <li><a class="dropdown-item" name="bat_temp" href="{% url 'tour:charts' 'bat_temp' %}">Baterie Kondensatorów</a></li>
                    <li><a class="dropdown-item" name="bat_temp" href="{% url 'tour:charts' 'rge_ac' %}">RGE-A,C</a></li>
                </ul>
            </li>
        </li>
    
        <li class="nav-item">
            <a class="nav-link {% if request.path == path_to_history %}active{% endif %}" href="{{ path_to_history }}">Historia</a>
        </li>
        <li class="nav-item">
            <a class="nav-link user {% if request.path == path_to_logout %}active{% endif %}" href="{{ path_to_logout }}">Wyloguj się, <i class="user">{{ user }}</i></a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link {% if request.path == path_to_login %}active{% endif %}" href="{{ path_to_login }}">Zaloguj się</a>
        </li>
    {% endif %}

</ul>