myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import  home_view, login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tour.urls')),
    path('index/', home_view, name='index'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject/tour/urls.py
# import pandas as pd
from django.urls import path
from . import views

app_name = 'tour'
urlpatterns = [
    path('', views.index, name='index'),
    path('new_tour', views.NewTour.as_view(), name='new-tour'),
    path('charts/<str:type_chart>', views.Charts.as_view(), name='charts'),
    path('history', views.History.as_view(), name="history"),
    path('edit_tour/<int:id>', views.edit_tour, name='edit-tour'),
    path('delete/<int:id>', views.delete_tour, name='delete-tour')
]

myproject/tour/forms.py
from django import forms
from .models import Tour


class TourForm(forms.ModelForm):
    class Meta:
        model = Tour
        fields = '__all__'


class Transformers(forms.Form):
    tr11 = forms.BooleanField(required=False)
    tr12 = forms.BooleanField(required=False)
    tr21 = forms.BooleanField(required=False)
    tr31 = forms.BooleanField(required=False)
    tr41 = forms.BooleanField(required=False)
    tr42 = forms.BooleanField(required=False)
    temp_A1 = forms.BooleanField(required=False, initial=True)
    temp_A2 = forms.BooleanField(required=False, initial=True)
    temp_A3 = forms.BooleanField(required=False, initial=True)
    temp_rdzen = forms.BooleanField(required=False)
    select_all = forms.BooleanField(required=False)


class UPSy(forms.Form):
    ups_1_34 = forms.BooleanField(required=False)
    ups_tt = forms.BooleanField(required=False)
    ups_GPD = forms.BooleanField(required=False)
    ups_BL04BM = forms.BooleanField(required=False)
    ups_BL06ID = forms.BooleanField(required=False)
    ups_BL04ID = forms.BooleanField(required=False)
    ups_BL10BM = forms.BooleanField(required=False)
    ups_BL09BM = forms.BooleanField(required=False)
    ups_BL05ID = forms.BooleanField(required=False)
    ups_PPOZ = forms.BooleanField(required=False)
    working_temp = forms.BooleanField(required=False)
    l1 = forms.BooleanField(required=False)
    l2 = forms.BooleanField(required=False)
    l3 = forms.BooleanField(required=False)
    load = forms.BooleanField(required=False)


class Capacitors_Battery(forms.Form):
    bat11 = forms.BooleanField(required=False)
    bat12 = forms.BooleanField(required=False)
    bat21 = forms.BooleanField(required=False)
    bat31 = forms.BooleanField(required=False)
    temp = forms.BooleanField(required=False)
    weekly_TPF = forms.BooleanField(required=False)


class RGEAC(forms.Form):
    rozdz_rge_ac = forms.BooleanField(required=False, initial=True)
    supply_tor_1 = forms.BooleanField(required=False)
    supply_tor_2 = forms.BooleanField(required=False)

myproject/tour/views.py
import re
from django.views import View
from django.views.generic import ListView
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TourForm, Transformers, UPSy, Capacitors_Battery, RGEAC
from .models import Tour
from .utils import get_plot
from datetime import datetime
import pandas as pd
from typing import Pattern

def index(request):
    message = None
    context = {'message': message}
    return render(request, 'tour/index.html', context=context)


class NewTour(View):

    date = datetime.now().strftime('%d-%m-%Y')
    message = None

    def get(self, request):        
        context = {
            'form': TourForm(),
            'date': self.date,
            'message': self.message
        }
        return render(request, 'tour/new_tour.html', context=context)

    def post(self, request):
        form = TourForm(request.POST)
        if form.is_valid():
            form.save()
            context = {
                'form': TourForm(),
                'message': "Obchód zapisany poprawnie."
            }
            return render(request, 'tour/new_tour.html', context=context)
        else:
            context = {
                'form': TourForm(),
                'message_bad': "Wystąpił błąd zapisu obchodu."
            }
            return render(request, 'tour/new_tour.html', context=context)


class Charts(View):
    
    def get(self, request, type_chart):
        context = {
            'transformers_form': Transformers(),
            'upsy_form': UPSy(),
            'cap_bat_form': Capacitors_Battery(),
            'rge_ac_form': RGEAC(),
            "type_chart": type_chart
        }
        return render(request, 'tour/charts.html', context=context)

    def post(self, request, type_chart):
        context = {}
        message = None
        
        # TRANSFORMATORY
        if 'button-submit-transformers' in request.POST:
            transformers_form = Transformers(request.POST)            
            devices, parameters = self.get_devices_and_parameters(transformers_form, r"tr\d{2}", [r"temp_."])            
            title = "Wykres temperaturowy Transformatorów"
            legend_device = [f"Trafo TR{device[-2:-1]}.{device[-1:]}" for device in devices]
            legend_parameter = [f"Czujnik {parameter[-2:]}" for parameter in parameters]
            legends = [f"{dev}, {par}" for dev in legend_device for par in legend_parameter]
            ylabel = "Temperatura [℃]"
            context['transformers_form'] = transformers_form

        # UPSy
        if 'button-submit-upsy' in request.POST:
            upsy_form = UPSy(request.POST)
            devices, parameters = self.get_devices_and_parameters(upsy_form, r"ups_.", [r"working_temp", r"l\d", r"load"]) 
            if 'load' in parameters and any(l in parameters for l in ['l1', 'l2', 'l3']):
                message = "Źle wybrane parametry"
            elif 'load' in parameters and any(d in devices for d in ["ups_1_34", "ups_tt", "ups_GPD", "ups_BL04BM", "ups_BL06ID", "ups_BL04ID", "ups_BL10BM", "ups_BL09BM"]):
                message = "Źle dobrane parametry. UPS 3faz. do obciążenia Omegi."
            elif any(l in parameters for l in ['l1', 'l2', 'l3']) and any(d in devices for d in ["ups_BL05ID", "ups_PPOZ"]):
                message = "Źle dobrane parametry. Omega do obciążenia 3faz."
            else:
                if 'working_temp' in parameters:                    
                    title = "Wykres temperaturowy UPSów"
                    legends = [f"UPS {device[4:]}" for device in devices]
                    ylabel = "Temperatura [℃]"          
                elif 'load' in parameters:                    
                    title = "Wykres obciążenia UPSów Omega"            
                    legends = [f"UPS {device[4:]}" for device in devices]
                    ylabel = 'Obciążenie [VA]'
                elif 'l1' or 'l2' or 'l3' in parameters:                    
                    title = "Wykres obciążenia UPSów"            
                    legend_dev = [f"UPS {device[4:]}" for device in devices]
                    legend_par = ["Faza {}".format(parameter.capitalize()) for parameter in parameters]
                    legends = [f"{i}, {j}" for i in legend_dev for j in legend_par]
                    ylabel = 'Obciążenie [%]'
            context['upsy_form'] = upsy_form
        
        # BATERIE KONDENSATORÓW
        if 'button-submit-cap-battery' in request.POST:
            legends = None
            cap_bat_form = Capacitors_Battery(request.POST)
            devices, parameters = self.get_devices_and_parameters(cap_bat_form, r"bat\d{2}", [r"temp", r"weekly_TPF"])
            if 'temp' in parameters:
                title = "Wykres temperaturowy Baterii Kondensatorów"
                legends = [f"Bateria RG{device[-2:-1]}.{device[-1:]}" for device in devices]
                ylabel = "Temperatura [℃]"
            elif 'weekly_TPF' in parameters:
                title = "Wykres TPF baterii kondensatorów"            
                legend_dev = [f"Bateria RG{device[-2:-1]}.{device[-1:]}" for device in devices]
                legend_par = [f"{parameter[:6].capitalize()}{parameter[6:].upper()}" for parameter in parameters]
                legends = [f"{i}, {j}" for i in legend_dev for j in legend_par]
                ylabel = 'Tygodniowe TPF'
            context['cap_bat_form'] = cap_bat_form

        # RGE-A,C        
        if 'button-submit-rge-ac' in request.POST:
            rge_ac_form = RGEAC(request.POST)
            devices, parameters = self.get_devices_and_parameters(rge_ac_form, r"rozdz_rge_ac", [r"supply_tor_\d{1}"]) 
            title = "Rozdzielnica RGE-A,C - zasilanie"
            legends = [f"Zasilanie - tor {number[-1:]}" for number in parameters]
            ylabel = "Napięcie [V]"
            context['rge_ac_form'] = rge_ac_form
        
        try:
            context.update(
                {
                'chart': self.charts(ydata=self.char_values(devices, parameters), title=title, legends=legends, ylabel=ylabel)
                }
            )
        except:
            pass
        finally:
            context.update(
                {
                "type_chart": type_chart,
                "message": message
                }
            )
            return render(request, 'tour/charts.html', context=context)
    
    def charts(self, **kwargs):
        '''Function generating chart.'''
        ydata = kwargs['ydata']
        title = kwargs['title']
        legends = kwargs['legends']
        ylabel = kwargs['ylabel']        
        chart = get_plot(df=ydata, title=title, legends=legends, ylabel=ylabel)
        return chart
    
    def get_devices_and_parameters(self, form, reg_device: Pattern, reg_parameter_list: list[Pattern]):
        '''Generator making two lists, for choosen devices and choosen parameters'''
        devices = [device for device in form.data if re.match(reg_device, device)]
        parameters = [parameter for parameter in form.data if any(re.match(reg, parameter) for reg in reg_parameter_list)]
        yield devices
        yield parameters
    
    def char_values(self, devices: list[str], parameters: list[str]):
        '''Function generating DataFrame from choosen option by user.'''
        columns = [f"{device}_{parameter}" for device in devices for parameter in parameters]        
        xdata = Tour.objects.values_list('date', flat=True)
        dates = [date.strftime('%Y-%m-%d') for date in xdata]
        data = Tour.objects.values(*columns)
        df = pd.DataFrame(data=data, index=dates)
        df = df.sort_index(ascending=True)
        return df


class History(ListView):
    template_name = "tour/history.html"
    paginate_by = 10
    model = Tour
    ordering = ["-date"]
    context_object_name = "tours"
    
    def get_queryset(self):
        start_date = self.request.GET.get('date-from')
        end_date = self.request.GET.get('date-to')
        queryset = super().get_queryset()
        if start_date and end_date:
            queryset = Tour.objects.filter(date__range=[start_date, end_date]).order_by('-date')
        return queryset


def edit_tour(request, id):
    tour = get_object_or_404(Tour, pk=id)
    form = TourForm(request.POST or None, instance=tour)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(to='tour:history')
        else:
            pass
    context = {
        'form': form
    }
    return render(request, 'tour/edit_tour.html', context=context)

def delete_tour(request, id):
    tour = get_object_or_404(Tour, pk=id)
    if request.method == 'POST':
        tour.delete()
        return redirect(to='tour:history')
    return render(request, 'tour/delete_tour.html', {'tour': tour})

myproject/tour/templates/tour/charts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Charts
{% endblock title %}

{% block content %}
    {% if message %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
    {% endif %}
    
    <table class="table table-bordered table-sm caption-top">
        <caption>Wybierz dane do wykresu</caption>
        <thead>
            <tr>
                <th scope="col">Urządzenie</th>
                <th scope="col">Parametry</th>
                <th scope="col">Akcje</th>
            </tr>
        </thead>
        <tbody>
            
            <form action="" method="POST">
                {% csrf_token %}

                <!--TRANSFORMERS FORM-->
                {% if type_chart == 'trafo_temp' %}
                    <tr>
                        <td>
                            <div class="form-check">{{ transformers_form.tr11 }} Transformator TR 1.1</div>
                            <div class="form-check">{{ transformers_form.tr12 }} Transformator TR 1.2</div>
                            <div class="form-check">{{ transformers_form.tr21 }} Transformator TR 2.1</div>
                            <div class="form-check">{{ transformers_form.tr31 }} Transformator TR 3.1</div>
                        </td>
                        <td>
                            <div><strong>Temperatura Pracy</strong></div>
                            <div class="form-check">{{ transformers_form.temp_A1 }} Czujnik A1</div>
                            <div class="form-check">{{ transformers_form.temp_A2 }} Czujnik A2</div>
                            <div class="form-check">{{ transformers_form.temp_A3 }} Czujnik A3</div>
                        </td>

                        <td>
                            <button type="submit" name="button-submit-transformers" class="btn btn-outline-success btn-sm">Pokaż wykres</button>
                        </td>
                    </tr>

                <!--UPSy FORM-->
                {% elif type_chart == 'ups_temp' %}
                    <tr>
                        <td>
                            <div><strong>UPSy 3faz.</strong></div>
                            <div class="form-check">{{ upsy_form.ups_1_34 }} UPS 1.34</div>
                            <div class="form-check">{{ upsy_form.ups_tt }} UPS TT</div>
                            <div class="form-check">{{ upsy_form.ups_GPD }} UPS GPD</div>
                            <div class="form-check">{{ upsy_form.ups_BL04BM }} UPS BL04BM</div>
                            <div class="form-check">{{ upsy_form.ups_BL06ID }} UPS BL06ID</div>
                            <div class="form-check">{{ upsy_form.ups_BL04ID }} UPS BL04ID</div>
                            <div class="form-check">{{ upsy_form.ups_BL10BM }} UPS BL10BM</div>
                            <div class="form-check">{{ upsy_form.ups_BL09BM }} UPS BL09BM</div>
                            <div><strong>UPSy 1faz.</strong></div>
                            <div class="form-check">{{ upsy_form.ups_BL05ID }} UPS BL05ID Omega</div>
                            <div class="form-check">{{ upsy_form.ups_PPOZ }} UPS PPOZ Omega</div>
                        </td>
                        <td>
                            <div><strong>Temperatura Pracy</strong></div>
                            <div class="form-check">{{ upsy_form.working_temp }} Temperatura Pracy</div>
                            <div><strong>Obciążenie UPSy 3faz.</strong></div>
                            <div class="form-check">{{ upsy_form.l1 }} Obciążenie, faza L1</div>
                            <div class="form-check">{{ upsy_form.l2 }} Obciążenie, faza L2</div>
                            <div class="form-check">{{ upsy_form.l3 }} Obciążenie, faza L3</div>
                            <div><strong>Obciążenie UPSy 1faz. Omega</strong></div>
                            <div class="form-check">{{ upsy_form.load }} Obciążenie</div>
                        </td>                    
                        <td>
                            <button type="submit" name="button-submit-upsy" class="btn btn-outline-success btn-sm">Pokaż wykres</button>
                        </td>
                    </tr>

                <!--CAPACITORS BATTERY FORM-->
                {% elif type_chart == 'bat_temp' %}
                    <tr>
                        <td>
                            <div class="form-check">{{ cap_bat_form.bat11 }} Bateria Kondensatorów dla RG1.1</div>
                            <div class="form-check">{{ cap_bat_form.bat12 }} Bateria Kondensatorów dla RG1.2</div>
                            <div class="form-check">{{ cap_bat_form.bat21 }} Bateria Kondensatorów dla RG2.1</div>
                            <div class="form-check">{{ cap_bat_form.bat31 }} Bateria Kondensatorów dla RG3.1</div>
                        </td>
                        <td>
                            <div><strong>Temperatura Pracy</strong></div>
                            <div class="form-check">{{ cap_bat_form.temp }} Temperatura Pracy</div>
                            <div><strong>Weekly TPF</strong></div>
                            <div class="form-check">{{ cap_bat_form.weekly_TPF }} Weekly TPF</div>
                        </td>                    
                        <td>
                            <button type="submit" name="button-submit-cap-battery" class="btn btn-outline-success btn-sm">Pokaż wykres</button>
                        </td>
                    </tr>

                <!--RGE-A,C switchboard FORM-->
                {% elif type_chart == 'rge_ac' %}
                    <tr>
                        <td>
                            <div class="form-check">{{ rge_ac_form.rozdz_rge_ac }} Rozdzielnica RGE-A,C</div>
                        </td>                            
                        <td>
                            <div class="form-check">{{ rge_ac_form.supply_tor_1 }} Zasilanie tor 1</div>
                            <div class="form-check">{{ rge_ac_form.supply_tor_2 }} Zasilanie tor 2</div>
                        </td>                    
                        <td>
                            <button type="submit" name="button-submit-rge-ac" class="btn btn-outline-success btn-sm">Pokaż wykres</button>
                        </td>
                    </tr>
                {% endif %}
                
            </form>
        </tbody>
    </table>

    <div class="container text-center chart">
        {% if chart %}
            {{ chart|safe }}
        {% endif %}
    </div>
{% endblock content %}

myproject/tour/templates/tour/delete_tour.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Charts
{% endblock title %}

{% block content %}
    <div class="alert alert-danger" role="alert">
        <strong>Czy na pewno chcesz usunąć ten obchód?</strong><br>
        Obchód z dnia: {{ tour.date|safe }}
    </div>
    <div class="container px-4 text-center">
        <form action="" method='POST'>
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger btn-sm">Tak, usuń ten obchód</button>
        </form>
        <a href="{% url 'tour:history' %}"><button class="btn btn-outline-success btn-sm">Cofnij</button></a>
    </div>
{% endblock content %}

myproject/tour/templates/tour/history.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Tour History
{% endblock title %}

{% block content %}
    <table class="table table-bordered table-sm caption-top">
        <caption><h5 class="text-center">Historia obchodów</h5></caption>
        <thead>
            <tr>
                <th scope="col">Data</th>
                <th scope="col">Wykonał</th>
                <th scope="col">Akcje</th>
            </tr>
        </thead>

        {% for tour in tours %}
                <tbody>
                    <tr>
                        <td>{{ tour.date|safe }}</td>
                        <td>{{ tour.author }}</td>
                        <td>
                            <a href="{% url 'tour:edit-tour' tour.id %}"><button class="btn btn-outline-success btn-sm">Edytuj</button></a>
                            <a href="{% url 'tour:delete-tour' tour.id %}"><button name="deleting" class="btn btn-outline-danger btn-sm">Usuń</button></a>
                        </td>
                    </tr>
                </tbody> 
        {% endfor %}
        
        {% include 'tour/includes/period.html' with form=form %}

    </table>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">

            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">poprzedni</a>
                    <a class="page-link" href="?page=1">Pierwszy</a>
                </li>
            {% endif %}

            <li class="page-item"><a class="page-link disabled" href="#">Arkusz {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}</a></li>

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">następny</a>
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Ostatni</a>
                </li>
            {% endif %}

        </ul>
    </nav>
{% endblock content %}

myproject/tour/templates/tour/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
        {% if message %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endif %}

        <h5 class="text-center">Obchody infrastruktury elektroenergetycznej SN i nN w Narodowym Centrum Promieniowania Synchrotronowego w Krakowie.</h5>
        <img src={% static 'solaris.png' %} class="rounded mx-auto d-block" alt="solaris_picture">

{% endblock content %}

myproject/tour/templates/tour/tour_result.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Tour Edited
{% endblock title %}

{% block content %}

    {% if "edit_tour" %}
        <div class="alert alert-success" role="alert">
            Obchód z dnia: {{ date|safe }} został edytowany poprawnie.
        </div>
    {% endif %}

    {% if "new_tour" %}
        <div class="alert alert-success" role="alert">
            Obchód z dnia: {{ date|safe }} został zapisany poprawnie.
        </div>
    {% endif %}

{% endblock content %}